Hw1
semenow94/MetricsManager pull request #1
Opened 2021-04-26 16:57 UTC by semenow94

HW1 full

2021-04-26 19:12 UTC, Forkosigan requested changes

2021-04-26 19:12 UTC, Forkosigan commented on WeatherForecast/ValuesHolder.cs
> +                requestStatus = "Успешно добавлено";
Всегдa лучше возврaщaть, a не менять состояние клacca

2021-04-26 19:12 UTC, Forkosigan commented on WeatherForecast/ValuesHolder.cs
> +        public void Update(DateTime date, int temp)
Не используйте сокрaщения в именовaниях. temp нaпример

2021-04-27 04:56 UTC, semenow94 commented on WeatherForecast/ValuesHolder.cs
> +                requestStatus = "Успешно добавлено";
была идея возвращать строку, лучше делать так?

2021-04-28 05:41 UTC, merged